export const pricingVersion = "2026-10-01";
export const serviceIds = ["openai", "r2", "d1", "workers", "durable_objects", "workflows", "workers_builds", "access", "github_actions", "domain"] as const;
export type ServiceId = typeof serviceIds[number];
export interface ServiceDefinition {
  id: ServiceId; name: string; plainLanguageName: string; purpose: string; featuresUsingIt: string[];
  failureImpact: string; planAndCostType: string; freeAllowanceSummary: string; freeLimits: Record<string,number>;
  accountOwnerRole: string; registrationRequired: boolean; setupSummary: string; dashboardPath: string;
  officialDocsUrl: string; secretAndBindingNames: string[]; usageMetricSource: string; monthlyChecks: string[];
  backupOrExitProcedure: string; replacementOptions: string; pricingCheckedAt: string; manualUpdatedAt: string;
}
const common = {accountOwnerRole:"운영자 1명",registrationRequired:true,monthlyChecks:["사용량과 무료 플랜 확인","공식 가격표 확인"],
  backupOrExitProcedure:"기존 결과·DB·키를 먼저 보존하고 승인된 환경만 변경",replacementOptions:"기존 자료를 보존한 뒤 운영자와 별도 검토",
  pricingCheckedAt:"2026-10-01T00:00:00.000Z",manualUpdatedAt:"2026-10-01"};
export const serviceRegistry: readonly ServiceDefinition[] = [
  {...common,id:"openai",name:"OpenAI API",plainLanguageName:"설교 이해 도우미",purpose:"교정·의도·요약·답과 단서 생성",featuresUsingIt:["관리자 생성"],failureImpact:"새 AI 생성 중단; 기존 퀴즈·출력 유지",planAndCostType:"사용량 과금 · 인프라 비용과 별도",freeAllowanceSummary:"무료 운영에 포함하지 않음",freeLimits:{},setupSummary:"nonprod/production Project 분리, content Worker에만 키 연결",dashboardPath:"OpenAI Platform → Usage / Costs",officialDocsUrl:"https://developers.openai.com/api/docs/pricing",secretAndBindingNames:["OPENAI_API_KEY"],usageMetricSource:"app_events · 과거 관측 가격표 보존"},
  {...common,id:"r2",name:"Cloudflare R2",plainLanguageName:"비공개 백업 창고",purpose:"SQL gzip 정상본 8개와 별도 삭제 기록",featuresUsingIt:["백업","복원"],failureImpact:"장기 백업 중단; 기존 파일 보존",planAndCostType:"Standard 무료 포함량 + 초과 과금 가능",freeAllowanceSummary:"10 GB-month · Class A 100만 · B 1,000만/월",freeLimits:{storageBytes:10_000_000_000,classA:1_000_000,classB:10_000_000},setupSummary:"private Standard bucket을 backup에만 연결; public/r2.dev 비활성",dashboardPath:"Storage & databases → R2 → Metrics / Billing → Billable Usage",officialDocsUrl:"https://developers.cloudflare.com/r2/pricing/",secretAndBindingNames:["BACKUP_BUCKET"],usageMetricSource:"cloudflare_graphql · 계정/백업 bucket"},
  {...common,id:"d1",name:"Cloudflare D1",plainLanguageName:"퀴즈·제출 장부",purpose:"정식 자료와 감사·운영 기록",featuresUsingIt:["발행","제출","마감"],failureImpact:"조회·저장·제출 실패",planAndCostType:"Workers Free · 초과 시 중단",freeAllowanceSummary:"read 500만/write 10만/UTC일 · 전체 저장 5 GB · Time Travel 7일",freeLimits:{rowsRead:5_000_000,rowsWritten:100_000,storageBytes:5_000_000_000},setupSummary:"환경별 D1 분리·검토된 migration 순차 적용",dashboardPath:"Storage & databases → D1 → Metrics / Time Travel",officialDocsUrl:"https://developers.cloudflare.com/d1/platform/pricing/",secretAndBindingNames:["DB","D1_REST_API_TOKEN","D1_DATABASE_ID"],usageMetricSource:"cloudflare_graphql · 계정/DB"},
  {...common,id:"workers",name:"Cloudflare Workers",plainLanguageName:"사이트와 서버",purpose:"Static Assets와 공개 API·비공개 background 실행",featuresUsingIt:["전체 웹앱"],failureImpact:"API 중단",planAndCostType:"Workers Free · Paid 변경은 별도 승인",freeAllowanceSummary:"요청 10만/UTC일 · 일반 invocation CPU 10ms",freeLimits:{requests:100_000},setupSummary:"main은 보호된 Preview 자동 배포; Production은 검수한 묶음을 수동 배포",dashboardPath:"Workers & Pages → Metrics / Settings",officialDocsUrl:"https://developers.cloudflare.com/workers/platform/pricing/",secretAndBindingNames:["SESSION_PEPPER","ARCHIVE_CURSOR_SECRET","CONTENT_WORKFLOW","BACKUP_WORKFLOW","CLOUDFLARE_ANALYTICS_TOKEN"],usageMetricSource:"cloudflare_graphql · 계정/각 Worker"},
  {...common,id:"durable_objects",name:"Durable Objects",plainLanguageName:"관리자 계산 공간",purpose:"기존 AdminCompute 계산 처리",featuresUsingIt:["관리자 API"],failureImpact:"관리자 요청 503; 공개 경로 유지",planAndCostType:"Free SQLite · 일반 Worker와 다른 실행 한도",freeAllowanceSummary:"요청 10만/일 · 13,000 GB-s/일 · SQLite만 Free",freeLimits:{requests:100_000,durationGbSeconds:13_000},setupSummary:"Preview와 Production의 별도 SQLite AdminCompute 연결",dashboardPath:"Workers & Pages → Durable Objects",officialDocsUrl:"https://developers.cloudflare.com/durable-objects/platform/pricing/",secretAndBindingNames:["ADMIN_COMPUTE"],usageMetricSource:"cloudflare_graphql · GB-s 확인 불가 값은 미확인"},
  {...common,id:"workflows",name:"Cloudflare Workflows",plainLanguageName:"중단·재개 작업 순서",purpose:"콘텐츠 생성과 백업 단계 연결",featuresUsingIt:["콘텐츠","백업"],failureImpact:"진행 중 job 실패/대기; 상태 확인 후 명시 재개",planAndCostType:"Free · 요청은 Workers와 공유",freeAllowanceSummary:"3,000 step/일 · state 1 GB-month · invocation CPU 10ms",freeLimits:{steps:3_000,storageBytes:1_000_000_000},setupSummary:"공개 route 없이 환경별 Workflow 내부 binding",dashboardPath:"Workers & Pages → Workflows",officialDocsUrl:"https://developers.cloudflare.com/workflows/reference/pricing/",secretAndBindingNames:["CONTENT_WORKFLOW","BACKUP_WORKFLOW"],usageMetricSource:"cloudflare_graphql · 관측 event, billed steps/state storage는 별도 확인"},
  {...common,id:"workers_builds",name:"Workers Builds",plainLanguageName:"Preview 자동 갱신",purpose:"main push의 Preview build",featuresUsingIt:["Preview 배포"],failureImpact:"새 build 중단; 직전 배포 유지",planAndCostType:"Free",freeAllowanceSummary:"3,000 build minutes/월",freeLimits:{buildMinutes:3_000},setupSummary:"Node24.18.0·pnpm11.14.0; Production 자동 배포 미연결",dashboardPath:"Workers & Pages → Builds",officialDocsUrl:"https://developers.cloudflare.com/workers/ci-cd/builds/limits-and-pricing/",secretAndBindingNames:[],usageMetricSource:"provider_api · 분 한도 도달 여부, 정확한 누적 분은 dashboard 확인"},
  {...common,id:"access",name:"Cloudflare Access",plainLanguageName:"관리자 로그인 문",purpose:"허용 관리자 보호",featuresUsingIt:["Preview 전체","관리자 UI/API"],failureImpact:"관리자 로그인 불가; JWT 확인 실패는 닫힘",planAndCostType:"Zero Trust Free",freeAllowanceSummary:"조직 전체 활성 고유 사용자 50명",freeLimits:{activeSeats:50},setupSummary:"Cloudflare account Allow·6시간·Everyone/Bypass 금지",dashboardPath:"Zero Trust → Team & Resources → Users",officialDocsUrl:"https://www.cloudflare.com/sase/products/access/",secretAndBindingNames:["ACCESS_TEAM_DOMAIN","ACCESS_AUD"],usageMetricSource:"provider_api · Access/Gateway seat 전체 합계, 권한 없으면 미확인"},
  {...common,id:"github_actions",name:"GitHub Actions",plainLanguageName:"자동 검사",purpose:"코드·migration·브라우저 검사",featuresUsingIt:["CI"],failureImpact:"배포 전 검사 확인 불가",planAndCostType:"공개 repo standard runner 무료",freeAllowanceSummary:"private/larger runner 변경 전 비용 재확인",freeLimits:{},setupSummary:"repository 설정과 runner 확인; 자동 유료 전환 금지",dashboardPath:"GitHub → Actions / Settings → Billing",officialDocsUrl:"https://docs.github.com/en/billing/concepts/product-billing/github-actions",secretAndBindingNames:[],usageMetricSource:"configured · runner/repo 상태 확인"},
  {...common,id:"domain",name:"서비스 주소",plainLanguageName:"교인 접속 주소",purpose:"공개 사이트 주소",featuresUsingIt:["접속"],failureImpact:"주소 만료 시 접속 실패",planAndCostType:"workers.dev USD 0 · 사용자 도메인은 연간 등록비",freeAllowanceSummary:"현재 사용자 도메인 미연결",freeLimits:{},registrationRequired:false,setupSummary:"Production 주소는 P8-02 합의 후 연결",dashboardPath:"등록기관 → 갱신 / Workers → Domains & Routes",officialDocsUrl:"https://developers.cloudflare.com/workers/configuration/routing/",secretAndBindingNames:[],usageMetricSource:"configured · 실제 등록한 도메인만"},
];
export const noSeparateCharge = ["Turnstile", "React", "Vite", "Tailwind", "Hono", "Drizzle"] as const;
