import { useEffect, useState } from "react";
import { policyListSchema, policyTestResultSchema } from "../../../shared/api/admin-weekly";
import { weeklyRequest } from "./client";
import { AdminNavigation } from "./Dashboard";
import styles from "./weekly.module.css";
const paths={reserved:'reserved-names',term:'moderation-terms',exception:'moderation-exceptions'} as const;
export function Component(){
  const [items,setItems]=useState<ReturnType<typeof policyListSchema.parse>['items']>([]),[loaded,setLoaded]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
  const [kind,setKind]=useState<keyof typeof paths>('reserved'),[value,setValue]=useState(''),[aliases,setAliases]=useState(''),[scope,setScope]=useState('comment'),[mode,setMode]=useState('exact'),[reason,setReason]=useState(''),[ack,setAck]=useState(false);
  const [test,setTest]=useState(''),[testScope,setTestScope]=useState('comment'),[result,setResult]=useState<ReturnType<typeof policyTestResultSchema.parse>|null>(null);
  useEffect(()=>{const controller=new AbortController();void Promise.all(Object.values(paths).map(path=>weeklyRequest(`/api/admin/${path}`,policyListSchema,'GET',undefined,controller.signal))).then(data=>{if(!controller.signal.aborted){setItems(data.flatMap(d=>d.items));setLoaded(true);}}).catch(()=>{if(!controller.signal.aborted)setMessage('보호 목록을 불러오지 못했습니다. 다시 시도해 주세요.');});return()=>controller.abort();},[attempt]);
  async function mutate(path:string,method:string,body:unknown){if(busy)return;setBusy(true);setMessage('');try{setItems((await weeklyRequest(`/api/admin/${path}`,policyListSchema,method,body)).items);setMessage('필터 목록을 저장했습니다.');return true;}catch(error){setMessage(error instanceof Error?error.message:'저장을 확인하지 못했습니다.');return false;}finally{setBusy(false);}}
  return <div className={styles.page}><AdminNavigation/><header className={styles.hero}><h2>이름·문구 필터 관리</h2><p>보호 이름은 이름 입력에만 적용합니다. 금지 문구와 정확한 예외는 범위를 나누어 관리합니다.</p></header>
    {message&&<p role="status">{message}</p>}<button type="button" disabled={busy} onClick={()=>setAttempt(a=>a+1)}>목록 다시 불러오기</button>
    <section className={styles.panel}><h3>필터 등록</h3><form onSubmit={e=>{e.preventDefault();void mutate(paths[kind],'POST',kind==='reserved'?{label:value,aliases:aliases.split('\n').map(a=>a.trim()).filter(Boolean)}:kind==='term'?{value,scope,matchMode:mode}:{value,scope,reason,acknowledged:ack});}}>
      <fieldset disabled={busy||!loaded} className={styles.fields}><legend>실제 이름과 목록은 관리자만 볼 수 있습니다.</legend><label>등록 종류<select value={kind} onChange={e=>{setKind(e.target.value as typeof kind);setScope('comment');setAck(false);}}><option value="reserved">보호 이름</option><option value="term">금지 문구</option><option value="exception">정확한 예외</option></select></label>
      <label>{kind==='reserved'?'보호 대상 표시명':'필터 문구'}<input value={value} required maxLength={200} onChange={e=>setValue(e.target.value)}/></label>
      {kind==='reserved'?<label>이름·별칭 (한 줄에 하나)<textarea required rows={4} value={aliases} onChange={e=>setAliases(e.target.value)}/></label>:<label>적용 범위<select value={scope} onChange={e=>setScope(e.target.value)}><option value="name">이름</option><option value="comment">코멘트</option><option value="answer">답안</option>{kind==='term'&&<option value="all">모두</option>}</select></label>}
      {kind==='term'&&<label>일치 방식<select value={mode} onChange={e=>setMode(e.target.value)}><option value="exact">전체 일치</option><option value="contains">포함</option></select></label>}
      {kind==='exception'&&<><label>예외 사유<input value={reason} required minLength={2} maxLength={500} onChange={e=>setReason(e.target.value)}/></label><p>예외는 해당 범위의 정규화된 전체 문구가 정확히 같을 때만 금지 규칙을 건너뜁니다. 연락처·입력 형식·보호 이름 검사는 유지됩니다.</p><label><input type="checkbox" checked={ack} required onChange={e=>setAck(e.target.checked)}/>이 문구가 기존 금지 규칙을 건너뛰는 영향을 확인했습니다.</label></>}
      <button type="submit">필터 등록</button></fieldset></form></section>
    <section className={styles.panel}><h3>시험 문구</h3><form onSubmit={e=>{e.preventDefault();setResult(null);setBusy(true);void weeklyRequest('/api/admin/moderation-test',policyTestResultSchema,'POST',{scope:testScope,value:test}).then(setResult).catch(error=>setMessage(error instanceof Error?error.message:'시험하지 못했습니다.')).finally(()=>setBusy(false));}}><div className={styles.fields}><label>시험할 범위<select value={testScope} onChange={e=>setTestScope(e.target.value)}><option value="name">이름</option><option value="comment">코멘트</option><option value="answer">답안</option></select></label><label>시험 문구<input value={test} maxLength={1000} onChange={e=>setTest(e.target.value)}/></label><button disabled={busy||!loaded}>저장 없이 시험</button></div></form>
      {result&&<p role="status">{result.blocked?'차단':'허용'} · 정규화: {result.normalizedValue||'(빈 문자열)'}{result.matchedRuleId&&` · 일치 규칙: ${result.matchedRuleId}`}</p>}</section>
    <section><h3>등록된 보호 목록</h3>{loaded&&items.length===0&&<p>추가 목록이 없습니다. 기본 예약 이름·입력 형식 검사는 계속 적용됩니다.</p>}<ul className={styles.list}>{items.map(item=><li key={`${item.id}/${item.updatedAt}`} className={styles.panel}><h4>{item.label}</h4><p>{item.kind==='reserved'?'보호 이름':item.kind==='term'?'금지 문구':'정확한 예외'} · {item.value} · {item.scope} · {item.matchMode} · {item.enabled?'활성':'비활성'}</p>
      <form onSubmit={e=>{e.preventDefault();const fields=new FormData(e.currentTarget);void mutate(`${paths[item.kind]}/${item.id}`,'PATCH',{value:String(fields.get('value')),enabled:fields.get('enabled')==='on',expectedUpdatedAt:item.updatedAt,reason:String(fields.get('reason'))});}}><div className={styles.fields}><label>변형 문구 수정<input name="value" required maxLength={200} defaultValue={item.value}/></label><label>변경 사유<input name="reason" required minLength={2} maxLength={500}/></label><label><input name="enabled" type="checkbox" defaultChecked={item.enabled}/>활성</label><button disabled={busy}>필터 변경 저장</button></div></form></li>)}</ul></section>
  </div>;
}
